name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./lcov.info
        directory: ./coverage
